export const SET_APP_NAME = 'SET_APP_NAME';
export const FETCH_STATIONS = 'FETCH_STATIONS';
export const FETCH_STATIONS_SUCCESS = 'FETCH_STATIONS_SUCCESS';
export const FETCH_STATIONS_FAIL = 'FETCH_STATIONS_FAIL';
