export const SET_APP_NAME = 'SET_APP_NAME';
export const RESET_BOOKS = 'RESET_BOOKS';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

// AUTH
export const HANDLE_AUTH = 'HANDLE_AUTH';
export const HANDLE_AUTH_SUCCESS = 'HANDLE_AUTH_SUCCESS';
export const HANDLE_AUTH_FAIL = 'HANDLE_AUTH_FAIL';
