export const SET_APP_NAME = 'SET_APP_NAME';

// BOOKS
export const RESET_BOOKS = 'RESET_BOOKS';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const RESET_ADD_BOOK = 'RESET_ADD_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

// AUTH
export const HANDLE_AUTH = 'HANDLE_AUTH';
export const HANDLE_AUTH_SUCCESS = 'HANDLE_AUTH_SUCCESS';
export const HANDLE_AUTH_FAIL = 'HANDLE_AUTH_FAIL';

// BOOKCASES
export const RESET_BOOKCASE = 'RESET_BOOKCASE';
export const FETCH_BOOKCASE = 'FETCH_BOOKCASE';
export const FETCH_BOOKCASE_SUCCESS = 'FETCH_BOOKCASE_SUCCESS';
export const FETCH_BOOKCASE_FAIL = 'FETCH_BOOKCASE_FAIL';

export const REMOVE_BOOK_FROM_BOOKCASE = 'REMOVE_BOOK_FROM_BOOKCASE';
export const REMOVE_BOOK_FROM_BOOKCASE_SUCCESS =
  'REMOVE_BOOK_FROM_BOOKCASE_SUCCESS';
export const REMOVE_BOOK_FROM_BOOKCASE_FAIL = 'REMOVE_BOOK_FROM_BOOKCASE_FAIL';
export const RESET_REMOVE_BOOK_FROM_BOOKCASE =
  'RESET_REMOVE_BOOK_FROM_BOOKCASE';

// AUTHORS
export const RESET_AUTHORS = 'RESET_AUTHORS';
export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAIL = 'FETCH_AUTHORS_FAIL';
